In [1]:
import pandas as pd
import numpy as np
from data_gen import X_s, Y_s

In [2]:
def board_gen(X,Y):
    sh = np.shape(X)
    for i in range(sh[0]):
        print(X[i],"\t",Y[i])

In [3]:
board_gen(X_s[0], Y_s[0])

[[[0]
  [0]
  [4]
  [3]
  [0]
  [0]
  [2]
  [0]
  [9]]

 [[0]
  [0]
  [5]
  [0]
  [0]
  [9]
  [0]
  [0]
  [1]]

 [[0]
  [7]
  [0]
  [0]
  [6]
  [0]
  [0]
  [4]
  [3]]

 [[0]
  [0]
  [6]
  [0]
  [0]
  [2]
  [0]
  [8]
  [7]]

 [[1]
  [9]
  [0]
  [0]
  [0]
  [7]
  [4]
  [0]
  [0]]

 [[0]
  [5]
  [0]
  [0]
  [8]
  [3]
  [0]
  [0]
  [0]]

 [[6]
  [0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [0]
  [5]]

 [[0]
  [0]
  [3]
  [5]
  [0]
  [8]
  [6]
  [9]
  [0]]

 [[0]
  [4]
  [2]
  [9]
  [1]
  [0]
  [3]
  [0]
  [0]]] 	 8


In [4]:
print(X_s[:2],"\n", Y_s[:2])

[array([[[[0],
          [0],
          [4],
          [3],
          [0],
          [0],
          [2],
          [0],
          [9]],

         [[0],
          [0],
          [5],
          [0],
          [0],
          [9],
          [0],
          [0],
          [1]],

         [[0],
          [7],
          [0],
          [0],
          [6],
          [0],
          [0],
          [4],
          [3]],

         [[0],
          [0],
          [6],
          [0],
          [0],
          [2],
          [0],
          [8],
          [7]],

         [[1],
          [9],
          [0],
          [0],
          [0],
          [7],
          [4],
          [0],
          [0]],

         [[0],
          [5],
          [0],
          [0],
          [8],
          [3],
          [0],
          [0],
          [0]],

         [[6],
          [0],
          [0],
          [0],
          [0],
          [0],
          [1],
          [0],
          [5]],

         [[0],
          [0],
          [